-- local dock = {
-- 	-- Item
-- 	icon = "__intermodal-logistics__/graphics/icon/large-container-dock.png",
-- 	icon_size = 32,
-- 	stack_size = 50,
-- 	place_result = "dock-dummy",
-- 	subgroup = "container-dock",
-- 	-- Base
-- 	name = "intermodal-logistics-large-container-dock",
-- 	type = "item",
-- 	order = "c",
-- };

-- data:extend { dock };
